# SPDX-FileCopyrightText: 2023 Carl Zeiss Microscopy GmbH
#
# SPDX-License-Identifier: LGPL-3.0-or-later
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Make non-blocking due to network timeouts etc.
DISABLE_LINTERS:
  - REPOSITORY_TRIVY  # this linter seems currently broken, so we disable it here for now
C_CPPLINT_ARGUMENTS: --verbose=2
CPP_CPPLINT_ARGUMENTS: --verbose=2
JSON_JSONLINT_ARGUMENTS: --comments # Allow comments in JSON files
DOCKERFILE_HADOLINT_ARGUMENTS: --ignore DL3008 # Ignore "pin versions in pip" warning
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: false
TEXT_REPORTER: true
EMAIL_REPORTER: false
VALIDATE_ALL_CODEBASE: true
