# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Make non-blocking due to network timeouts etc.
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: false
TEXT_REPORTER: true
EMAIL_REPORTER: false
# Uncomment before putting onto main
# CONFIG_REPORTER: false
VALIDATE_ALL_CODEBASE: true
